[tool.poetry]
name = "the-elements-of-statistical-learning"
version = "0.1.0"
description = ""
authors = ["Zhuyi Xue"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
